clc
close all
clear
filepath = {'results\Lab_wc_inter_repeat', ...
            'results\Lab_wc_across_calibration', ...
            'results\Field_inter_sensor\VWC', ...
            'results\Field_inter_sensor\NO3', ...
            'results\Field_inter_sensor\NH4', ...
            'results\Field_inter_sensor\totN', ...
            'results\Lab_N_inter_repeat\NO3', ...
            'results\Lab_N_inter_repeat\NH4', ...
            'results\Lab_N_inter_repeat\totN', ...
            'results\Lab_N_inter_repeat\Urea'};   

fs_method = {'MRMR', 'PLS_VIP', 'SPA', 'CARS'};        % MRMR or PLS_VIP
rg_model = {'PLS', 'SVM', 'ANN'}; % LR, SVM, PLS, ANN
plot_heatmap(filepath{10}, fs_method, rg_model, 'LC')

